### ISSUE TITLE
Unable to override hardcoded background color

### ISSUE THREAD

**Issue by fiv** [kyaroru/RNParallax#11]
I have an app where I use fullscreen background image and I have ReactNativeParallaxHeader inside of the ImageBackground like:

```
<ImageBackground source={images.background} style={{ flex: 1, width: null, height: null }}...>
  <ReactNativeParallaxHeader .../>
</ImageBackground>
```

Currently this library creates fullscreen `<View style={styles.container}>` container with hardcoded background color:
```
container: {
    backgroundColor: 'white',
    flex: 1,
  },
```
This container hides my background image completely. I did not find any ways to bypass this, except modifying the library source code by setting container ` backgroundColor` to `"transparent"`.

So maybe change the default value to transparent or make it configurable through props?

**Comment by kyaroru** [comment]
hi, noted on that.. will make it configurable 😋 thanks for the suggestion

**Comment by fiv** [comment]
Great! Thanks :)

**Comment by kyaroru** [comment]
> Great! Thanks :)

Hi @fiv I have updated in [v1.1.2](https://github.com/kyaroru/RNParallax/tree/v1.1.2)
