### ISSUE TITLE
Title and navbar shows same time

### ISSUE THREAD

**Issue by hadesownage** [kyaroru/RNParallax#13]
How we can avoid this ?

https://i.imgur.com/pVbzeYK.png

**Comment by kyaroru** [comment]
Hi @hadesownage you can try this
```
alwaysShowTitle={false}
alwaysShowNavBar={false}
```

**Comment by hadesownage** [comment]
@kyaroru

Hello, I already use this settings, the problem is when the page doesn't have enough content, the title and navbar will show at the same time.

**Comment by kyaroru** [comment]
hmm.. that's actually one of the issue i am trying to fix 😬

**Comment by hadesownage** [comment]
You can try something with snapToInterval on ScrollView

**Comment by kyaroru** [comment]
hmm nt working
