### ISSUE TITLE
回到顶部的操作

### ISSUE THREAD

**Issue by thisSillyCow** [kyaroru/RNParallax#14]
作者 我想问一下 如果数据比较多的情况下 有没有一个回到顶部的方法或者事件啊 我这边尝试了几种还是不行

**Comment by kyaroru** [comment]
你好 @thisSillyCow，获许你可以尝试通过`scrollViewProps`的`ref`来达到你要的效果。。如下：
```jsx
<RNParallax
  scrollViewProps={{
    ref: (ref) => { this.scrollView = ref.getNode(); },
  }}
/>
```
之后在`onButtonPress`内
```js
onButtonPress = () => {
  this.scrollView.scrollTo({ x: 0, y: 0 });
}
```

**Comment by thisSillyCow** [comment]
好的 谢谢 我这边自己找到解决方法了

**Comment by thisSillyCow** [comment]
title 怎么添加 点击事件 我这边尝试了几种还是不行

**Comment by kyaroru** [comment]
可以参考我的代码https://github.com/kyaroru/Flowy/blob/master/src/containers/dashboard/index.js
在68行`onNavBarPress`

**Comment by thisSillyCow** [comment]
谢谢楼主这个是点击回到顶部的 我想说的是 renderHeaderTitle() 里面怎么加点击事件 我这边有个点击操作 就是不知道怎么实现

**Comment by kyaroru** [comment]
可以参考98行 `renderTitle()` 和 132行`title={this.renderTitle()}`

**Comment by thisSillyCow** [comment]
好的 谢谢你 我这边参考一下

**Comment by thisSillyCow** [comment]
还是不行 楼主 谢谢你的提议 我自己把依赖改了 来适配这边的逻辑

**Comment by ugrdursun** [comment]
> ```js
> this.scrollView.scrollTo({ x: 0, y: 0 });
> ```

What is .getNode function is for here ? I am receiving an error with that. without it, its not working. Error throws .scrollTo is undefined.

Do you know any updated solution ?

**Comment by ugrdursun** [comment]
> 你好 @thisSillyCow，获许你可以尝试通过`scrollViewProps`的`ref`来达到你要的效果。。如下：
> 
> ```js-jsx
> <RNParallax
>   scrollViewProps={{
>     ref: (ref) => { this.scrollView = ref.getNode(); },
>   }}
> />
> ```
> 
> 之后在`onButtonPress`内
> 
> ```js
> onButtonPress = () => {
>   this.scrollView.scrollTo({ x: 0, y: 0 });
> }
> ```

What is .getNode function is for here ? I am receiving an error with that. without it, its not working. Error throws .scrollTo is undefined.

Do you know any updated solution ?
