### ISSUE TITLE
Can I share sample sources?

### ISSUE THREAD

**Issue by gilra2000** [kyaroru/RNParallax#15]
thanks^^

**Comment by kyaroru** [comment]
hi what do you mean? @gilra2000

**Comment by gilra2000** [comment]
I want to see the demo source code.

**Comment by kyaroru** [comment]
Perhaps you can have a look here: https://github.com/kyaroru/Flowy/blob/master/src/containers/dashboard/index.js

It is my personal project and I have modified some of the code inside RNParallax

**Comment by gilra2000** [comment]
wow~! great! thanks^^
