### ISSUE TITLE
Same Gif

### ISSUE THREAD

**Issue by huuluan97** [kyaroru/RNParallax#17]
https://camo.githubusercontent.com/2c57c48d34be620d9d51d37176d423d4e994fcfe/68747470733a2f2f692e6779617a6f2e636f6d2f32343334336532313237623865343739613532663462633538353365663435372e676966 

Hello Kyaroru thank you, you save my life but you can help build parallax same gif.
Thank you so much.

**Comment by kyaroru** [comment]
I can't understand what do you mean.. you can ask in Chinese 😛

**Comment by EssamSoft** [comment]
I think he need the example code like gif demo

**Comment by 0xpaperhead** [comment]
@huuluan97 You can pass any component to the title prop according to the documentation.
for the "Cash" icon and style when nav bar is show while scrolling, You can achieve that by changing your renderNavBar function to return something else other than a back icon on the left
