### ISSUE TITLE
Hide navbar title in parallax header

### ISSUE THREAD

**Issue by webdevsyd** [kyaroru/RNParallax#22]
Hi

I have this issue wherein the title props is immediately displayed in the parallax header. Is there a way that the title will only be displayed once I scroll?

<img width="400" alt="Screen Shot 2019-04-14 at 11 29 45 AM" src="https://user-images.githubusercontent.com/15810023/56087951-b377cb80-5ea8-11e9-81f3-68c97af106eb.png">

**Comment by kyaroru** [comment]
@webdevsyd perhaps u can try `alwaysShowTitle={false}` & `alwaysShowNavBar={false}`

**Comment by webdevsyd** [comment]
I already did that but the title will not be displayed in the navigation bar when the user scroll the screen. What I wanted is only hide it in the parallax header.

**Comment by kyaroru** [comment]
then you should place the title in renderNavBar i think 🤔
