### ISSUE TITLE
Header Component instead of just image?

### ISSUE THREAD

**Issue by Saad-Bashar** [kyaroru/RNParallax#23]
<img width="429" alt="Screen Shot 2019-04-18 at 6 48 22 PM" src="https://user-images.githubusercontent.com/13269141/56356134-90cc1680-620a-11e9-83de-0e06388fe472.png">

Can I do something like this?

**Comment by kyaroru** [comment]
I afraid not, the parallax effect is applied to the image. But you can always fork and change it to suit your preference :)

**Comment by Saad-Bashar** [comment]
Ahh, okay I think I will do it :) Thanks for the response.

**Comment by ManigandanRaamanathan** [comment]
@Saad-Bashar its possible to modify content. I have pulled a request for merge.
![image](https://user-images.githubusercontent.com/22089729/74152555-7f487500-4c49-11ea-8689-cd99acfa172d.png)
