### ISSUE TITLE
extraScrollHeight prop is not working

### ISSUE THREAD

**Issue by dienast** [kyaroru/RNParallax#3]
It looks like extraScrollHeight is not functional. The default is 50, but changing it to e.g. 80 has no effect.

**Comment by dienast** [comment]
I found a sloppy workaround by adding an addition height to the main View.
So for example:
` <View style={{ marginTop: this.getHeaderMaxHeight(), height: 900 }}>`

at: https://github.com/kyaroru/RNParallax/blob/223d27164a627eeb6d4488a84e05519d003b0707/index.js#L295

**Comment by kyaroru** [comment]
Hi, it will be no effect if you're using Android because Android does not have elastic scrolling (the bounce effect) 😉

**Comment by dienast** [comment]
Well, the main problem is that now you can only show a maximum number of items approximately between 12 and 20 (depending on the resolution and screensize of your device). With my workaround you can increase the height of the view so you can have more items visible.

**Comment by kyaroru** [comment]
i think the extraScrollHeight is not related to your issue right. extraScrollHeight is for the elastic scrolling effect... it wont affect your view port

**Comment by kyaroru** [comment]
your issue is about the whole parallax header height right?

**Comment by dienast** [comment]
Yeah, that's correct.
