### ISSUE TITLE
How to use swipe to refresh?

### ISSUE THREAD

**Issue by trananh0810** [kyaroru/RNParallax#33]
Hello,

How to use swipe to refresh?

Thank in advance!

**Comment by kyaroru** [comment]
Hi, you can try to use scrollViewProps as below (not tested yet)
`scrollViewProps={{
  refreshControl: <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
}}`

**Comment by skanwarjeet** [comment]
Hi,
I'm facing a problem with this code
`scrollViewProps={{ refreshControl: <RefreshControl refreshing={refreshing} onRefresh={onRefresh} /> }}`

I'm not able to change colour of refresh control. I'm passing tintColor = "red" but it's still picking default colour. tintColor is working for scroll view and flatList but not in this package. any idea why?
