### ISSUE TITLE
Navbar Object 

### ISSUE THREAD

**Issue by zapcriativo** [kyaroru/RNParallax#34]
Hi
Is it possible to use a component instead of the title, for example a button that moves according to the header resize?

example: https://github.com/i6mi6/react-native-parallax-scroll-view/blob/master/demo.ios.0.17.2.gif

**Comment by kyaroru** [comment]
Hi, the title props can be anything
title | any | No | This is the title to be display in the header, can be string or component

**Comment by zapcriativo** [comment]
Hello,

Thanks for the feedback, and how to continue using the paralax image in the navbar? Is it replaced by color?

**Comment by kyaroru** [comment]
Hi, you can specify backgroundImage

backgroundImage | image source | No | This renders the background image of the header (if specified, background color will not take effect) | Default to null
