### ISSUE TITLE
Module break, not scrolling

### ISSUE THREAD

**Issue by Angelk90** [kyaroru/RNParallax#5]
@kyaroru : 
Hi, I tried the form here is the example link: https://snack.expo.io/r1Ck3agvM
As you can see, it does not allow the elements in the tab to be scrolled.
I would also like the tab to crash when the toolbar reaches the minimum height.
That is, it should scroll only the elements of the tab, without scrolling the tab.
How can I do?

**Comment by kyaroru** [comment]
hi @Angelk90 I tested your expo app, it is scrollable now. I believe you've found the fix 😉 sorry for late reply though... because my mailbox categorized emails from github as spam for some reason..

**Comment by Angelk90** [comment]
@kyaroru :  I do not understand. I have not found any solution.

**Comment by kyaroru** [comment]
i tested your expo app and i can scroll your tab contents

**Comment by Angelk90** [comment]
@kyaroru : 
It can not be on android it does not work, the elements do not flow at all
there are only eight elements that appear and do not flow, if you see the array there are many more elements.

**Comment by kyaroru** [comment]
Hmm... if i remove the tab component, it works fine.. so i think there's issue between them. Kindly check this out https://snack.expo.io/B1tACYGtz Perhaps you can try using different tab view component or build one yourself for android 😉

**Comment by Angelk90** [comment]
@kyaroru :  I tried any tab that I found for react-native, same problem. So you're saying that your module can not be used together with a Tab View?

**Comment by kyaroru** [comment]
Hmm.. why my self made Tabs is working? Check this out: https://snack.expo.io/SJjrrqMFf
Please build 1 yourself 😉 It requires only little effort

**Comment by Angelk90** [comment]
@kyaroru : Hmm .. But the tabs should not scroll should remain fixed under the actionbar, it should only shrink the contents of the tab.
Ideas on what the problem might be?

**Comment by FranclisJunior** [comment]
+1 
Hi I would need in this case a parallax header with tabs attached below the header after the scroll, something like: 
![screenshot from 2018-11-10 19-31-29](https://user-images.githubusercontent.com/2888106/48306841-5ce41b00-e51f-11e8-92f1-2045baf83037.png)

**Comment by ugrdursun** [comment]
Hello @Angelk90 , Do you remember how did you solve the problem ?

 I am using react-native-scrollable-tab-view and can't scroll  (only in android same as you), even scrollenabled is false for scrollable tab content.
