### ISSUE TITLE
TypeError: renderContent is not a function

### ISSUE THREAD

**Issue by ghost** [kyaroru/RNParallax#6]
Hi,

I tried to run this on my test app and kept getting the  'TypeError: renderContent is not a function'.

I haven't made any changes to your code, could you please assist with this?

![simulator screen shot - iphone x - 2018-05-20 at 16 15 20](https://user-images.githubusercontent.com/3904952/40276274-2f1c11e6-5c49-11e8-95b2-5ff38ddd32ea.png)

**Comment by kyaroru** [comment]
Hi, you have to declare `renderContent()` method in your component in order to use it. the same goes to `renderNavBar()`
example...
```
renderContent() {
  return (
    <View><Text>hi</Text></View>
  );
}

render() {
  return (
    <View style={styles.container}>
      <ReactNativeParallaxHeader
        headerMinHeight={120}
        headerMaxHeight={170}
        extraScrollHeight={20}
        navbarColor={Colors.primary}
        title={'Parallax Header :p'}
        titleStyle={styles.titleStyle}
        backgroundImage={viewImages.background}
        backgroundImageScale={1.2}
        renderNavBar={this.renderNavBar}
        renderContent={this.renderContent}
      />
    </View>
  );
}
```

**Comment by ghost** [comment]
Very sorry, I should have read the [Documentation](https://github.com/kyaroru/RNParallax/blob/master/README.md)

Thanks for the help 👍
