### ISSUE TITLE
Crashing on setting a value to renderNavBar using states

### ISSUE THREAD

**Issue by nHiRanZ** [kyaroru/RNParallax#7]
Hi, the library works fine except for this issue.

```
render() {
        return (
            <View style={styles.mainContainer}>
                <ReactNativeParallaxHeader
                    headerMinHeight={100}
                    headerMaxHeight={250}
                    extraScrollHeight={0}
                    navbarColor={AppConfigurations.branding.appThemeColour}
                    backgroundImage={require('./../../images/kiosk-starter-page/background.jpg')}
                    backgroundImageScale={1}
                    renderNavBar={this.renderNavBar}
                    renderContent={this.renderContent}
                />
            </View>
        );
    }

renderNavBar() {
        return(
            <View style={{flex: 1, flexDirection: 'column', justifyContent: 'flex-end', padding: 20}}>
                <Text>{this.state.userName}</Text>
            </View>
        )
    }
```

State is simply an empty string and the following error gets printed.

![simulator screen shot - ipad pro 9 7-inch - 2018-05-22 at 14 45 52](https://user-images.githubusercontent.com/7906605/40353350-ed730a92-5dce-11e8-9545-d57b6c890b36.png)

Also, is there a way to add an blur overlay or gradient over the parallax image? Thank you.

**Comment by kyaroru** [comment]
yo, please check for undefined, it might be the state is not having default value..

**Comment by nHiRanZ** [comment]
Fix was to bind the method in the constructor. Can't believe I missed it.

PS: Any solution for adding a blur or gradient to the parallax image?

**Comment by kyaroru** [comment]
hmmm.. currently it is hard to achieve blur effect unless the image source itself is already a blurred image 🤔

**Comment by nHiRanZ** [comment]
We can do something like having an option to disable the navbar and have the title to be component rather than a string. So that title component could have the blur or gradient styles that would go over the image?

**Comment by kyaroru** [comment]
hmmm.. yea you can implement that.. but that's depends on personal preference
