### ISSUE TITLE
PropTypes missmatch at titleStyle props

### ISSUE THREAD

**Issue by achmadk** [kyaroru/RNParallax#8]
According to [README](https://github.com/kyaroru/RNParallax), `titleStyle`'s proptypes is `style`. Unfortunately, when I try to change `fontFamily` and `fontSize` style attribute value into `titleStyle` props, I got `Warning: Failed prop type of type 'object', expected number` warning message.

**Comment by kyaroru** [comment]
opps.. it might be possible that you didn't use StyleSheet.create() for your style..
```
const styles = StyleSheet.create({
  myStyle: {
    padding: 10,
  },
});
```
using this will cause the styles.myStyle result in number propTypes

**Comment by armandomendivil** [comment]
I have the same issue, this is my code using StyleSheet.create

    <ReactNativeParallaxHeader titleStyle={styles.titleStyle} ... 
    const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      titleStyle: {
        fontSize: 16,
      },
    });
