### ISSUE TITLE
this.props.navigation.navigate it is working without parallax-header but with parallax header not working  ?

### ISSUE THREAD

**Issue by osamamostafa1** [kyaroru/RNParallax#9]
![a](https://user-images.githubusercontent.com/26348775/45524629-b9e97c00-b7cf-11e8-9f6a-5e456e6fbdcb.PNG)
![aa](https://user-images.githubusercontent.com/26348775/45524661-ddacc200-b7cf-11e8-9e0a-d76f04c6e190.PNG)

**Comment by kyaroru** [comment]
hmmm.. will get back in few days.. was on vacation 😛

**Comment by BukhariMuslim** [comment]
Can you access `this.props.navigation` on `render()` as well?
I think there is no problem with parallax header. You might want to read about using `this` on [medium article](https://medium.freecodecamp.org/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56).

And this might relate to #7

**Comment by kyaroru** [comment]
@osamamostafa1 perhaps you can try
```
renderContent = () => {
  ...
}
```
instead of just
```
renderContent() {
  ...
}
```

sorry for late reply, missed this issue out >_<
